<?php

namespace Database\Seeders;

use App\Models\Tour;
use App\Models\Duration;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TourSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tours = [
            [
                'title' => 'Cairo Pyramids Day Tour',
                'overview' => 'Explore the ancient wonders of Egypt with our comprehensive Cairo Pyramids tour. Visit the Great Pyramid of Giza, Sphinx, and learn about ancient Egyptian civilization.',
                'slug' => 'cairo-pyramids-day-tour',
                'duration_id' => 1,
                'adult_price' => 150.00,
                'child_price' => 100.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 1,
                'code' => 'TOUR001',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Luxor Valley of Kings Adventure',
                'overview' => 'Discover the tombs of ancient pharaohs in the Valley of the Kings. Explore the magnificent temples and learn about the New Kingdom period.',
                'slug' => 'luxor-valley-of-kings-adventure',
                'duration_id' => 3,
                'adult_price' => 280.00,
                'child_price' => 200.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 2,
                'code' => 'TOUR002',
                'duration_in_days' => 2,
            ],
            [
                'title' => 'Aswan Nile Cruise Experience',
                'overview' => 'Cruise along the majestic Nile River and visit historic temples. Experience the beauty of the Nile Valley and ancient Egyptian monuments.',
                'slug' => 'aswan-nile-cruise-experience',
                'duration_id' => 4,
                'adult_price' => 450.00,
                'child_price' => 350.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 3,
                'code' => 'TOUR003',
                'duration_in_days' => 3,
            ],
            [
                'title' => 'Egypt Complete Heritage Tour',
                'overview' => 'Comprehensive tour covering all major historical sites in Egypt. From Cairo to Luxor to Aswan, experience the full Egyptian heritage.',
                'slug' => 'egypt-complete-heritage-tour',
                'duration_id' => 5,
                'adult_price' => 750.00,
                'child_price' => 600.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 4,
                'code' => 'TOUR004',
                'duration_in_days' => 5,
            ],
            [
                'title' => 'Alexandria Coastal Discovery',
                'overview' => 'Explore the Mediterranean coast and ancient Alexandria. Visit the Library of Alexandria, Pompey\'s Pillar, and the Catacombs.',
                'slug' => 'alexandria-coastal-discovery',
                'duration_id' => 6,
                'adult_price' => 920.00,
                'child_price' => 750.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 5,
                'code' => 'TOUR005',
                'duration_in_days' => 7,
            ],
            [
                'title' => 'Sinai Desert Safari',
                'overview' => 'Adventure through the stunning Sinai desert landscape. Experience Bedouin culture and visit Mount Sinai and St. Catherine\'s Monastery.',
                'slug' => 'sinai-desert-safari',
                'duration_id' => 7,
                'adult_price' => 1200.00,
                'child_price' => 1000.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 6,
                'code' => 'TOUR006',
                'duration_in_days' => 10,
            ],
            [
                'title' => 'Red Sea Diving Adventure',
                'overview' => 'Discover the underwater wonders of the Red Sea. Professional diving instruction and equipment provided.',
                'slug' => 'red-sea-diving-adventure',
                'duration_id' => 2,
                'adult_price' => 250.00,
                'child_price' => 180.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 7,
                'code' => 'TOUR007',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Cairo Islamic Architecture Tour',
                'overview' => 'Explore the magnificent Islamic architecture of Cairo. Visit historic mosques, madrasas, and Islamic monuments.',
                'slug' => 'cairo-islamic-architecture-tour',
                'duration_id' => 1,
                'adult_price' => 120.00,
                'child_price' => 80.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 8,
                'code' => 'TOUR008',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Luxor East Bank Temples',
                'overview' => 'Visit the magnificent temples on Luxor\'s East Bank. Explore Karnak Temple Complex and Luxor Temple.',
                'slug' => 'luxor-east-bank-temples',
                'duration_id' => 1,
                'adult_price' => 180.00,
                'child_price' => 130.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 9,
                'code' => 'TOUR009',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Aswan High Dam & Philae Temple',
                'overview' => 'Visit the engineering marvel of the High Dam and the beautiful Philae Temple. Learn about modern and ancient Egypt.',
                'slug' => 'aswan-high-dam-philae-temple',
                'duration_id' => 1,
                'adult_price' => 160.00,
                'child_price' => 110.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 10,
                'code' => 'TOUR010',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Cairo Museum & Antiquities',
                'overview' => 'Visit the world-famous Egyptian Museum and discover ancient treasures. See the treasures of Tutankhamun.',
                'slug' => 'cairo-museum-antiquities',
                'duration_id' => 1,
                'adult_price' => 80.00,
                'child_price' => 50.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 11,
                'code' => 'TOUR011',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Luxor Hot Air Balloon Sunrise',
                'overview' => 'Float over the ancient monuments of Luxor in a hot air balloon. Breathtaking sunrise views of the Valley of the Kings.',
                'slug' => 'luxor-hot-air-balloon-sunrise',
                'duration_id' => 1,
                'adult_price' => 280.00,
                'child_price' => 180.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 12,
                'code' => 'TOUR012',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Cairo Food & Culture Experience',
                'overview' => 'Experience authentic Egyptian cuisine and local culture. Taste traditional dishes and learn about Egyptian food traditions.',
                'slug' => 'cairo-food-culture-experience',
                'duration_id' => 1,
                'adult_price' => 70.00,
                'child_price' => 45.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 13,
                'code' => 'TOUR013',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Nile Dinner Cruise & Entertainment',
                'overview' => 'Enjoy a romantic dinner cruise on the Nile with live entertainment. Experience Cairo\'s skyline from the water.',
                'slug' => 'nile-dinner-cruise-entertainment',
                'duration_id' => 1,
                'adult_price' => 160.00,
                'child_price' => 110.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 14,
                'code' => 'TOUR014',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Cairo Night Photography & Lights',
                'overview' => 'Capture stunning night photos of Cairo\'s illuminated landmarks. Professional photography guidance included.',
                'slug' => 'cairo-night-photography-lights',
                'duration_id' => 1,
                'adult_price' => 220.00,
                'child_price' => 160.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 15,
                'code' => 'TOUR015',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Dendera & Abydos Temple Heritage',
                'overview' => 'Visit the well-preserved temples of Dendera and Abydos. Explore ancient Egyptian religious architecture.',
                'slug' => 'dendera-abydos-temple-heritage',
                'duration_id' => 3,
                'adult_price' => 290.00,
                'child_price' => 210.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 16,
                'code' => 'TOUR016',
                'duration_in_days' => 2,
            ],
            [
                'title' => 'Hurghada Water Sports Adventure',
                'overview' => 'Experience thrilling water sports in Hurghada. Jet skiing, parasailing, and banana boat rides.',
                'slug' => 'hurghada-water-sports-adventure',
                'duration_id' => 1,
                'adult_price' => 200.00,
                'child_price' => 140.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 17,
                'code' => 'TOUR017',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Sharm El Sheikh Quad Biking',
                'overview' => 'Adventure quad biking in the Sinai desert. Experience the thrill of off-road desert exploration.',
                'slug' => 'sharm-el-sheikh-quad-biking',
                'duration_id' => 1,
                'adult_price' => 180.00,
                'child_price' => 120.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 18,
                'code' => 'TOUR018',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Dahab Blue Hole Diving',
                'overview' => 'Dive at the famous Blue Hole in Dahab. Advanced diving experience for certified divers.',
                'slug' => 'dahab-blue-hole-diving',
                'duration_id' => 1,
                'adult_price' => 350.00,
                'child_price' => 250.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 19,
                'code' => 'TOUR019',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Fayoum Oasis Day Trip',
                'overview' => 'Explore the beautiful Fayoum Oasis, known for its waterfalls and natural beauty. Visit Wadi El-Rayan and Lake Qarun.',
                'slug' => 'fayoum-oasis-day-trip',
                'duration_id' => 1,
                'adult_price' => 180.00,
                'child_price' => 120.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 20,
                'code' => 'TOUR020',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Cairo Coptic Churches Tour',
                'overview' => 'Discover the rich Christian heritage of Egypt. Visit the Hanging Church, St. Sergius Church, and Ben Ezra Synagogue.',
                'slug' => 'cairo-coptic-churches-tour',
                'duration_id' => 1,
                'adult_price' => 95.00,
                'child_price' => 65.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 21,
                'code' => 'TOUR021',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Hurghada Desert Safari',
                'overview' => 'Experience the thrill of desert safari in Hurghada. Quad biking, camel riding, and traditional Bedouin dinner.',
                'slug' => 'hurghada-desert-safari',
                'duration_id' => 1,
                'adult_price' => 160.00,
                'child_price' => 110.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => true,
                'display_order' => 22,
                'code' => 'TOUR022',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Sharm El Sheikh Snorkeling',
                'overview' => 'Explore the underwater world of Sharm El Sheikh. Snorkeling in the Red Sea with colorful coral reefs.',
                'slug' => 'sharm-el-sheikh-snorkeling',
                'duration_id' => 1,
                'adult_price' => 140.00,
                'child_price' => 90.00,
                'infant_price' => 0.00,
                'enabled' => true,
                'featured' => false,
                'display_order' => 23,
                'code' => 'TOUR023',
                'duration_in_days' => 1,
            ],
            [
                'title' => 'Disabled Tour Example',
                'overview' => 'This tour is disabled and should not be counted.',
                'slug' => 'disabled-tour-example',
                'duration_id' => 1,
                'adult_price' => 100.00,
                'child_price' => 80.00,
                'infant_price' => 0.00,
                'enabled' => false,
                'featured' => false,
                'display_order' => 24,
                'code' => 'TOUR024',
                'duration_in_days' => 1,
            ],
        ];

        foreach ($tours as $tourData) {
            // Check if tour already exists
            $existingTour = Tour::where('slug', $tourData['slug'])->first();
            
            if ($existingTour) {
                // Tour already exists, skip creation
                continue;
            }
            
            $durationId = $tourData['duration_id'];
            unset($tourData['duration_id']);

            $tour = Tour::create($tourData);
            
            // Associate tour with duration
            $duration = Duration::find($durationId);
            if ($duration) {
                $duration->tours()->attach($tour->id);
            }
        }

        // Update tours_count for all durations
        Duration::all()->each(function ($duration) {
            $duration->setToursCount();
        });

        $this->command->info('Tours seeded successfully!');
    }
}

